const statusEl=document.querySelector('#status'),summary=document.querySelector('#summary'),changed=document.querySelector('#changed'),failed=document.querySelector('#failed'),next=document.querySelector('#next'),proofs=document.querySelector('#proofs'),commentPanel=document.querySelector('#commentPanel'),commentText=document.querySelector('#commentText'),commentList=document.querySelector('#commentList'),commentStatus=document.querySelector('#commentStatus');
function esc(value){return String(value??'').replace(/[&<>"']/g,(match)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[match]));}
function list(el,items,empty){const source=Array.isArray(items)&&items.length?items:[empty];el.innerHTML=source.map((item)=>`<li>${esc(item)}</li>`).join('');}
function setCommentStatus(message,kind=''){commentStatus.className=`comment-status ${kind}`.trim();commentStatus.textContent=message;}
function renderFeedback(events){if(!Array.isArray(events)||events.length===0){commentList.innerHTML='<li>No persisted feedback yet.</li>';return;}commentList.innerHTML=events.slice().reverse().map((event)=>{const created=event.created_at?new Date(event.created_at).toLocaleString():'unknown time';const target=event.target||'live-result-viewer';return `<li><strong>${esc(created)}</strong> <span>${esc(target)}</span><br>${esc(event.text)}<br><span class="muted">route=${esc(event.routed_status||'unrouted')} · mission=${esc(event.mission_id||'none')} · resolved=${esc(event.resolved??false)}</span></li>`;}).join('');}
async function loadFeedback(){try{const response=await fetch('/api/visual-feedback',{cache:'no-store'});if(!response.ok)throw new Error(`feedback ${response.status}`);const payload=await response.json();renderFeedback(payload.events);}catch(err){commentList.innerHTML=`<li>Feedback replay degraded: ${esc(err.message)}</li>`;}}
async function loadJson(url,fallback={}){try{const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`${url} ${r.status}`);return await r.json();}catch(err){return {...fallback,_error:err.message};}}
async function load(){try{const [state,trace,worker,routing]=await Promise.all([loadJson('/result-state.json'),loadJson('/state/latest-trace-summary.json'),loadJson('/state/worker-smoke.json'),loadJson('/state/visual-feedback-routing.json')]);statusEl.className='badge ok';statusEl.textContent=`${state.status||'unknown'} · ${new Date(state.updated_at||Date.now()).toLocaleTimeString()}`;summary.innerHTML=[`<dt>Browser status</dt><dd>${esc(state.browser_status)}</dd>`,`<dt>Live URL</dt><dd>${esc(state.live_url||location.href)}</dd>`,`<dt>Arena URL</dt><dd>${esc(state.arena_url||'not started')}</dd>`,`<dt>Worker smoke</dt><dd>${esc(worker.status||'unknown')}</dd>`,`<dt>Trace Crystal</dt><dd>${esc(trace.summary_file||'none')}</dd>`,`<dt>Feedback routed</dt><dd>${esc(routing.routed_count??0)} routed · ${esc(routing.rejected_count??0)} rejected</dd>`,`<dt>Comment Mode</dt><dd>${esc(state.comment_mode||'persisted + routable')}</dd>`].join('');list(changed,state.what_changed,'Empty state: no changes projected yet.');list(failed,state.what_still_failed,'Success state: no current failures listed.');next.textContent=state.next_repair_action||'No next action recorded.';proofs.textContent=JSON.stringify({latest_proof_bundle:state.latest_proof_bundle,validation_logs:state.validation_logs,proof_bundles:state.proof_bundles,screenshots:state.screenshots,trace_summary:trace,worker_smoke:worker},null,2);}catch(err){statusEl.className='badge error';statusEl.textContent=`Live viewer degraded: ${err.message}`;}}
document.querySelector('#toggleComments').onclick=async()=>{commentPanel.hidden=!commentPanel.hidden;if(!commentPanel.hidden)await loadFeedback();};
document.querySelector('#saveComment').onclick=async()=>{const text=commentText.value.trim();if(!text){setCommentStatus('Write a note before saving.','bad');return;}setCommentStatus('Saving…');try{const response=await fetch('/api/visual-feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({target:'live-result-viewer',page_url:location.href,text})});const payload=await response.json().catch(()=>({}));if(!response.ok||payload.ok===false){throw new Error(payload.error||`feedback ${response.status}`);}commentText.value='';setCommentStatus('Saved to visual-feedback-events.jsonl. Master routing will create a proof-required mission.','ok');await loadFeedback();}catch(err){setCommentStatus(`Save failed: ${err.message}`,'bad');}};
loadFeedback();load();setInterval(load,2000);
