const statusEl=document.querySelector('#status'),summary=document.querySelector('#summary'),changed=document.querySelector('#changed'),failed=document.querySelector('#failed'),next=document.querySelector('#next'),proofs=document.querySelector('#proofs'),commentText=document.querySelector('#commentText'),commentList=document.querySelector('#commentList'),commentStatus=document.querySelector('#commentStatus'),pipelineNodes=document.querySelector('#pipelineNodes');
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
async function loadJson(url,fallback=null){try{const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`${url} ${r.status}`);return await r.json();}catch(err){if(fallback!==null)return {...fallback,_error:err.message};throw err;}}
async function loadAny(urls,fallback={}){for(const u of urls){const v=await loadJson(u,{_error:'missing'});if(!v._error)return v;}return fallback;}
function cls(status){const s=String(status||'unknown').toLowerCase();if(s.includes('full')||s.includes('pass')||s.includes('ok')||s.includes('resolved'))return 'ok';if(s.includes('degrad')||s.includes('pending')||s.includes('warn')||s.includes('not_proven'))return 'warn';if(s.includes('fail')||s.includes('block')||s.includes('reject')||s.includes('missing'))return 'err';return 'neutral';}
function chip(text,status=text){return `<span class="status-chip ${cls(status)}">${esc(text)}</span>`;}
function kv(obj){return Object.entries(obj||{}).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('');}
function list(el,items,empty){el.innerHTML=(items&&items.length)?items.map(i=>`<li>${esc(i)}</li>`).join(''):`<li>${esc(empty)}</li>`;}
function syntaxJson(obj){let json=JSON.stringify(obj,null,2)||'{}';json=json.replace(/\\/g,'/');return esc(json).replace(/(&quot;[^&]+?&quot;)(\s*:)/g,'<span class="json-key">$1</span>$2').replace(/:\s*(&quot;.*?&quot;)/g,': <span class="json-string">$1</span>').replace(/:\s*\b(true|false)\b/g,': <span class="json-boolean">$1</span>').replace(/:\s*(-?\d+(?:\.\d+)?)/g,': <span class="json-number">$1</span>').replace(/:\s*null/g,': <span class="json-null">null</span>');}
function renderFeedback(events){if(!Array.isArray(events)||events.length===0){commentList.innerHTML='<div class="feedback-row"><div class="meta">empty</div><div>No persisted feedback yet.</div></div>';return;}commentList.innerHTML=events.slice().reverse().slice(0,14).map(event=>{const created=event.created_at?new Date(event.created_at).toLocaleString():'unknown time';const target=event.target||'live-result-viewer';const status=event.feedback_status||event.routed_status||'new';return `<div class="feedback-row"><div class="meta">${esc(created)}</div><div class="meta">${esc(target)}</div><div>${esc(event.text)}<br><span class="meta">mission=${esc(event.mission_id||'none')} · proofs=${esc(Array.isArray(event.proof_refs)?event.proof_refs.length:0)}</span></div><div>${chip(status,status)}</div></div>`;}).join('');}
async function loadFeedback(){try{const response=await fetch('/api/visual-feedback',{cache:'no-store'});if(!response.ok)throw new Error(`feedback ${response.status}`);const payload=await response.json();renderFeedback(payload.events);}catch(err){commentList.innerHTML=`<div class="feedback-row"><div>${esc('Feedback replay degraded: '+err.message)}</div></div>`;}}
function setCommentStatus(text,kind=''){commentStatus.className=`comment-status ${kind}`;commentStatus.textContent=text;}
function node(name,status,detail){return `<div class="pipeline-node"><b>${esc(name)}</b><div class="node-status">${chip(status,status)}</div><p class="meta">${esc(detail||'')}</p></div>`;}
function renderPipeline(state,trace,worker,statusSummary,reality){const validation=statusSummary.validation_status?.status||state.validation_status||'unknown';const workerStatus=worker.status||statusSummary.worker_smoke?.status||'unknown';const traceStatus=trace.summary_file?'passed':'not_proven';const projection=statusSummary.operational_level||state.status||'unknown';const browser=reality.selected_browser_route||state.browser_status||'not_proven';pipelineNodes.innerHTML=[node('Validation',validation,statusSummary.latest_validation_bundle||''),node('Worker Smoke',workerStatus,statusSummary.latest_worker_proof||''),node('Trace Crystal',traceStatus,trace.summary_file||''),node('Projection',projection,statusSummary.updated_at||state.updated_at||''),node('Browser Proof',browser,statusSummary.latest_browser_proof||state.latest_proof_bundle||'')].join('');}
async function load(){try{const [state,trace,worker,routing,statusSummary,health,reality,proof]=await Promise.all([loadAny(['/api/result-state','/result-state.json'],{}),loadJson('/state/latest-trace-summary.json',{}),loadJson('/state/worker-smoke.json',{}),loadJson('/state/visual-feedback-routing.json',{}),loadAny(['/api/status','/state/status-summary.json'],{}),loadAny(['/api/health','/state/health.json'],{}),loadAny(['/api/browser','/state/reality-router.json'],{}),loadAny(['/api/proof'],{})]);const current=statusSummary.operational_level||state.status||health.status||'unknown';statusEl.className=`verdict status-chip ${cls(current)}`;statusEl.textContent=current;document.querySelector('#railMeta').textContent=`${statusSummary.branch||'branch unknown'} · ${new Date(state.updated_at||statusSummary.updated_at||Date.now()).toLocaleTimeString()} · loopback only`;document.querySelector('#sessionMeta').textContent=`validation ${statusSummary.validation_status?.run_id||'unknown'} · browser ${reality.selected_browser_route||state.browser_status||'unknown'}`;summary.innerHTML=kv({browser_status:state.browser_status||reality.browser_use_status||'unknown',live_url:state.live_url||location.href,arena_url:state.arena_url||statusSummary.arena_url||'not started',mission_control:state.mission_control_url||statusSummary.mission_control_url||'not started',worker_smoke:worker.status||'unknown',trace_crystal:trace.summary_file||'none',feedback_pipeline:`${routing.feedback_count??0} total · ${routing.routed_count??0} routed · ${routing.unresolved_count??0} unresolved · ${routing.rejected_count??0} rejected`,comment_mode:state.comment_mode||'persisted + routable'});renderPipeline(state,trace,worker,statusSummary,reality);list(changed,state.what_changed,'Empty state: no changes projected yet.');list(failed,state.what_still_failed,'Success state: no current failures listed.');next.textContent=state.next_repair_action||statusSummary.next_recommended_command||'No next action recorded.';proofs.innerHTML=syntaxJson({latest_proof_bundle:state.latest_proof_bundle||statusSummary.latest_browser_proof,validation_logs:state.validation_logs,proof_bundles:state.proof_bundles,screenshots:state.screenshots,trace_summary:trace,worker_smoke:worker,visual_feedback:routing,browser_reality:reality,api_proof:proof});}catch(err){statusEl.className='verdict status-chip err';statusEl.textContent=`Live viewer degraded: ${err.message}`;}}
document.querySelector('#toggleComments').onclick=async()=>{const panel=document.querySelector('#commentPanel');panel.hidden=!panel.hidden;document.querySelector('#toggleComments').setAttribute('aria-expanded',String(!panel.hidden));if(!panel.hidden)await loadFeedback();};
document.querySelector('#saveComment').onclick=async()=>{const text=commentText.value.trim();if(!text){setCommentStatus('Write a note before saving.','bad');return;}setCommentStatus('Saving…');try{const response=await fetch('/api/visual-feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({target:'live-result-viewer',page_url:location.href,text})});const payload=await response.json().catch(()=>({}));if(!response.ok||payload.ok===false){throw new Error(payload.error||`feedback ${response.status}`);}commentText.value='';setCommentStatus('Saved. Process-VisualFeedback.ps1 will route this into a proof-required mission.','ok');await loadFeedback();}catch(err){setCommentStatus(`Save failed: ${err.message}`,'bad');}};
document.querySelector('#copyProof').onclick=async()=>{try{await navigator.clipboard.writeText(proofs.innerText);document.querySelector('#copyProof').textContent='copied';setTimeout(()=>document.querySelector('#copyProof').textContent='copy json',1200);}catch{document.querySelector('#copyProof').textContent='select json';}};
load();loadFeedback();setInterval(()=>{load();loadFeedback();},3000);
