param([int]$Port=7575,[string]$Project='.',[int]$MaxRequests=0)
$ErrorActionPreference='Stop'; [Console]::OutputEncoding=[Text.UTF8Encoding]::new($false)
$GodRoot = Split-Path -Parent $PSScriptRoot
$StateDir = Join-Path $GodRoot 'state'
New-Item -ItemType Directory -Path $StateDir -Force | Out-Null
function Test-PortFree([int]$p){ try { $l=[Net.Sockets.TcpListener]::new([Net.IPAddress]::Parse('127.0.0.1'),$p); $l.Start(); $l.Stop(); return $true } catch { return $false } }
function Send-HttpResponse([IO.Stream]$Stream,[string]$Status,[string]$ContentType,[byte[]]$Bytes){ $header="HTTP/1.1 $Status`r`nContent-Type: $ContentType`r`nCache-Control: no-store`r`nContent-Length: $($Bytes.Length)`r`nConnection: close`r`n`r`n"; $hb=[Text.Encoding]::UTF8.GetBytes($header); $Stream.Write($hb,0,$hb.Length); $Stream.Write($Bytes,0,$Bytes.Length) }
function Send-Json([IO.Stream]$Stream,[string]$Status,$Value){ $json=$Value|ConvertTo-Json -Depth 40; Send-HttpResponse $Stream $Status 'application/json; charset=utf-8' ([Text.Encoding]::UTF8.GetBytes($json)) }
function Get-ContentType([string]$File){ $ext=[IO.Path]::GetExtension($File).ToLowerInvariant(); if($ext -eq '.html'){return 'text/html; charset=utf-8'} elseif($ext -eq '.js'){return 'text/javascript; charset=utf-8'} elseif($ext -eq '.css'){return 'text/css; charset=utf-8'} elseif($ext -eq '.json'){return 'application/json; charset=utf-8'} else {return 'text/plain; charset=utf-8'} }
function Read-JsonFile($Path,$Default){ if(Test-Path -LiteralPath $Path){ try { return Get-Content -LiteralPath $Path -Raw -Encoding UTF8 | ConvertFrom-Json } catch { return $Default } }; return $Default }
function Read-JsonLines($Path){ $rows=@(); if(Test-Path -LiteralPath $Path){ foreach($line in Get-Content -LiteralPath $Path -Encoding UTF8){ if([string]::IsNullOrWhiteSpace($line)){continue}; try { $rows += ($line|ConvertFrom-Json) } catch { $rows += [pscustomobject]@{schema_version=1;status='unreadable';source=$Path} } } }; return $rows }
function Get-QueueSnapshot { $depth=[ordered]@{}; $files=[ordered]@{}; foreach($q in @('pending','active','done','failed','replay','tournament','adversarial')){ $dir=Join-Path $GodRoot "queues/$q"; $items=@(Get-ChildItem -LiteralPath $dir -Filter '*.json' -ErrorAction SilentlyContinue | Sort-Object LastWriteTime -Descending | Select-Object -First 25 | ForEach-Object { $_.Name }); $depth[$q]=$items.Count; $files[$q]=$items }; return [ordered]@{schema_version=1;generated_at=(Get-Date).ToUniversalTime().ToString('o');depth=$depth;files=$files} }
function Read-FeedbackEvents { $events=Read-JsonLines (Join-Path $GodRoot 'live/visual-feedback-events.jsonl'); $routing=Read-JsonFile (Join-Path $StateDir 'visual-feedback-routing.json') ([ordered]@{events=@();rejected=@()}); $map=@{}; foreach($r in @($routing.events)){ if($r.event_id){$map[[string]$r.event_id]=$r} }; foreach($r in @($routing.rejected)){ if($r.event_id){$map[[string]$r.event_id]=$r} }; $out=@(); foreach($e in $events){ if($e.PSObject.Properties['id'] -and $map.ContainsKey([string]$e.id)){ $m=$map[[string]$e.id]; foreach($name in @('feedback_status','routed_status','mission_id','resolved','proof_required','proof_refs','duplicate_of_event_id')){ if($m.PSObject.Properties[$name]){ $e | Add-Member -NotePropertyName $name -NotePropertyValue $m.$name -Force } } } elseif(-not $e.PSObject.Properties['feedback_status']) { $e | Add-Member -NotePropertyName feedback_status -NotePropertyValue 'new' -Force }; $out += $e }; return $out }
function Get-Proofs { $browser=Get-ChildItem (Join-Path $GodRoot 'logs') -Recurse -Filter 'browser-proof.json' -ErrorAction SilentlyContinue | Sort-Object LastWriteTime -Descending | Select-Object -First 1; $validation=Get-ChildItem (Join-Path $GodRoot 'logs') -Filter 'godmode-validation-*.json' -ErrorAction SilentlyContinue | Sort-Object LastWriteTime -Descending | Select-Object -First 1; return [ordered]@{schema_version=1;generated_at=(Get-Date).ToUniversalTime().ToString('o');latest_browser_proof=if($browser){$browser.FullName}else{$null};latest_validation=if($validation){$validation.FullName}else{$null};worker_smoke=Read-JsonFile (Join-Path $StateDir 'worker-smoke.json') ([ordered]@{});latest_trace=Read-JsonFile (Join-Path $StateDir 'latest-trace-summary.json') ([ordered]@{})} }
while(-not(Test-PortFree $Port)){ $Port++ }
Set-Content -LiteralPath (Join-Path $StateDir 'mission-control-port.txt') -Value ([string]$Port) -Encoding UTF8
Set-Content -LiteralPath (Join-Path $StateDir 'mission-control.url') -Value "http://127.0.0.1:$Port/" -Encoding UTF8
$listener=[Net.Sockets.TcpListener]::new([Net.IPAddress]::Parse('127.0.0.1'),$Port); $listener.Start(); Write-Host "[MISSION-CONTROL] listening on http://127.0.0.1:$Port/"; $count=0
try { while($true){ $client=$listener.AcceptTcpClient(); $count++; try { $stream=$client.GetStream(); $reader=[IO.StreamReader]::new($stream,[Text.Encoding]::UTF8,$false,1024,$true); $req=$reader.ReadLine(); while($true){ $line=$reader.ReadLine(); if($null -eq $line -or $line -eq ''){break} }; $target='/'; if($req -match 'GET\s+([^\s]+)'){ $target=[Uri]::UnescapeDataString($Matches[1].Split('?')[0]) }; if($target -eq '/'){$target='/index.html'}; if($target -eq '/api/health'){ Send-Json $stream '200 OK' (Read-JsonFile (Join-Path $StateDir 'health.json') ([ordered]@{status='missing'})) }
elseif($target -eq '/api/status'){ Send-Json $stream '200 OK' (Read-JsonFile (Join-Path $StateDir 'status-summary.json') ([ordered]@{status='missing'})) }
elseif($target -eq '/api/queues'){ Send-Json $stream '200 OK' (Get-QueueSnapshot) }
elseif($target -eq '/api/processes'){ Send-Json $stream '200 OK' (Read-JsonFile (Join-Path $StateDir 'process-registry.json') ([ordered]@{components=@()})) }
elseif($target -eq '/api/traces'){ $recent=@(Get-ChildItem (Join-Path $GodRoot 'traces') -Filter '*.summary.json' -ErrorAction SilentlyContinue | Sort-Object LastWriteTime -Descending | Select-Object -First 10 | ForEach-Object { Read-JsonFile $_.FullName ([ordered]@{path=$_.FullName;status='unreadable'}) }); Send-Json $stream '200 OK' ([ordered]@{schema_version=1;latest=Read-JsonFile (Join-Path $StateDir 'latest-trace-summary.json') ([ordered]@{});recent=$recent}) }
elseif($target -eq '/api/proofs'){ Send-Json $stream '200 OK' (Get-Proofs) }
elseif($target -eq '/api/feedback'){ Send-Json $stream '200 OK' ([ordered]@{schema_version=1;events=@(Read-FeedbackEvents);routing=Read-JsonFile (Join-Path $StateDir 'visual-feedback-routing.json') ([ordered]@{})}) }
else { $map=@{'/index.html'='index.html';'/mission-control.js'='mission-control.js';'/mission-control.css'='mission-control.css';'/shared/operations-cathedral.css'='../shared/operations-cathedral.css'}; $bytes=$null; if($map.ContainsKey($target)){ $file=Join-Path $PSScriptRoot $map[$target]; if(Test-Path -LiteralPath $file){ $bytes=[IO.File]::ReadAllBytes($file); Send-HttpResponse $stream '200 OK' (Get-ContentType $file) $bytes } }; if($null -eq $bytes){ Send-HttpResponse $stream '404 Not Found' 'text/plain; charset=utf-8' ([Text.Encoding]::UTF8.GetBytes('not found')) } } } catch { try { Send-Json $stream '500 Internal Server Error' ([ordered]@{ok=$false;error=$_.Exception.Message}) } catch {} } finally { $client.Close() }; if($MaxRequests -gt 0 -and $count -ge $MaxRequests){break} } } finally { $listener.Stop() }

