param([string]$Project='.',[ValidateSet('safe','fullauto','yolo')][string]$Mode='safe',[switch]$Once)
$ErrorActionPreference='Stop'; [Console]::OutputEncoding=[Text.UTF8Encoding]::new($false)
$S=Split-Path -Parent $MyInvocation.MyCommand.Path
foreach($l in 'Common','Queue','Schema','Safety','Health','Arena','Live','Proof','TraceCrystal','SafePatch','CodexRouter','RealityRouter'){ . (Join-Path $S "lib/GodMode.$l.ps1") }
$root=Initialize-GodModeStructure $Project; $run=New-GodModeRunId; $mission=New-GodModeMissionObject $run 'ARCHITECT' 'First observation-only repo inspection' $false $false 1; Save-GodModeMission $Project $mission 'active'|Out-Null
& (Join-Path $S 'spawn-agent.ps1') -Project $Project -MissionId $run -Role ARCHITECT -Task $mission.task -DryRun | Out-Null
$processed=@(); $failed=@(); foreach($file in Get-ChildItem (Join-GodModePath $root 'inbox/results') -Filter '*.json' -ErrorAction SilentlyContinue){ try{ $res=Get-Content $file.FullName -Raw -Encoding UTF8|ConvertFrom-Json; $schema=Test-GodModeJsonLite $file.FullName (Get-GodModeSchemaRequiredKeys 'result'); if(-not $schema.ok){throw ('schema_lite_failed '+($schema.errors -join ','))}; $safe=Test-GodModeResultSafety $res $Project; if(-not $safe.ok){throw ('injection_gate_failed '+($safe.errors -join ','))}; $xp=25+(5*@($res.verified_claims).Count); Add-GodModeJsonLine (Join-GodModePath $root 'memory/experience-ledger.jsonl') @{schema_version=1;mission_id=$res.mission_id;role=$res.agent_role;status=$res.status;xp_awarded_by_host=$xp;stability=72;created_at=Get-GodModeIso;evidence_hashes=$res.evidence_hashes}; Add-GodModeJsonLine (Join-GodModePath $root 'memory/validation-history.jsonl') @{schema_version=1;mission_id=$res.mission_id;status='accepted';created_at=Get-GodModeIso;validation_results=$res.validation_results}; Move-Item $file.FullName (Join-GodModePath $root "queues/done/$($res.mission_id).result.json") -Force; $processed+=$res.mission_id } catch { $failed+=@{file=$file.FullName;error=$_.Exception.Message}; Move-Item $file.FullName (Join-GodModePath $root "queues/failed/$($file.BaseName).failed.json") -Force } }
$codex=Invoke-GodModeCodexRouter $Project; $reality=Invoke-GodModeRealityRouter $Project; $patch=Test-GodModeSafePatchRoute $Project
Update-GodModeDeityManifest $Project @() @(@{type='master_cycle';run_id=$run;processed=$processed;failed=$failed.Count;created_at=Get-GodModeIso})|Out-Null
$proofs=@(Get-ChildItem (Join-GodModePath $root 'traces') -Filter 'proof-*.json' -ErrorAction SilentlyContinue|sort LastWriteTime -Descending|select -First 3|%{$_.FullName}); $logs=@(Get-ChildItem (Join-GodModePath $root 'logs') -Filter '*.log' -ErrorAction SilentlyContinue|sort LastWriteTime -Descending|select -First 5|%{$_.FullName})
Update-GodModeLiveResult $Project @{status='ready';headline='Master observation cycle processed';browser_status='not browser-validated unless proof bundle exists';latest_proof_bundle=if($proofs.Count){$proofs[0]}else{$null};what_changed=@("Processed read-only missions: $($processed.Count)",'Updated deity manifest and live result projection.');what_still_failed=@($failed|%{$_.error})+@($reality.degraded_reasons);validation_logs=$logs;proof_bundles=$proofs;next_repair_action='Run validate-system.ps1 and start loopback dashboards.'}|Out-Null
Update-GodModeHealth $Project 'VERIFIED-MVP' @($reality.degraded_reasons) @() @{selected_codex_route=$codex.structured_worker_route;selected_browser_route=$reality.selected_browser_route;selected_patch_route=$patch.selected_route;live_result_status='ready';xp_awarded_by_host=(30*$processed.Count)}|Out-Null
Add-GodModeTraceSpan $Project $run 'master-controller-cycle' 'ok' @{processed=$processed;failed=$failed}|Out-Null; Write-Host "[DONE] Master cycle $run processed $($processed.Count), failed $($failed.Count)."
