param([string]$Project='.',[string]$MissionId,[string]$Role='ARCHITECT',[string]$Task='Read-only repo inspection',[switch]$DryRun)
$ErrorActionPreference='Stop'; [Console]::OutputEncoding=[Text.UTF8Encoding]::new($false)
$S=Split-Path -Parent $MyInvocation.MyCommand.Path
foreach($l in 'Common','Queue','Proof','TraceCrystal'){ . (Join-Path $S "lib/GodMode.$l.ps1") }
$root=Initialize-GodModeStructure $Project; if(-not $MissionId){$MissionId='mission-'+([guid]::NewGuid().ToString('N').Substring(0,12))}; $pp=Resolve-GodModeProjectPath $Project
$log=Join-GodModePath $root "logs/agent-$MissionId.log"; $cmds=@(); $git=Invoke-GodModeNativeCommand git @('status','-sb') $pp 20; $cmds+=@{command='git status -sb';exit_code=$git.exit_code;log=$log}
$pkg=Get-GodModePackageSnapshot $Project; $dev=Get-GodModeDevServerCandidates $Project; $val=Get-GodModeValidationCommandCandidates $Project
@("Agent role: $Role","Mission: $MissionId","Task: $Task","DryRun: $DryRun","Git status exit: $($git.exit_code)","Package exists: $($pkg.exists)","Dev candidates: $($dev.Count)","Validation candidates: $($val.Count)") | Set-Content $log -Encoding UTF8
$proof=New-GodModeProofBundle $Project $MissionId $cmds @('AGENTS.md','package.json','README.md'); $proofPath=Save-GodModeProofBundle $Project $proof
$result=@{schema_version=1;mission_id=$MissionId;agent_role=$Role;agent_profile_id=('entity-'+$Role.ToLowerInvariant());deity_name='Auralith Vector';deity_form='faceted circuit stag';tier='seed';level=1;status='success';concept_tree=@('repo','scripts','validation','live-preview');files_touched=@();commands_run=$cmds;validation_results=@(@{name='read_only_repo_inspection';status='passed';log=$log});browser_validation=$null;live_preview=$null;windows_route=$null;risks=@('read_only_dry_run_no_patch');issues_found=@();patches_made=@();failure_patterns=@();heuristics_learned=@('Prefer package scripts already declared by repo.');skills_suggested=@();recommended_next_missions=@('Run validate-system.ps1','Probe loopback dashboards');verified_claims=@(@{claim='Read-only ARCHITECT dry-run inspected package scripts and git status.';evidence=$log},@{claim='Proof bundle written.';evidence=$proofPath});unverified_claims=@();rejected_claims=@();evidence_hashes=@{agent_log=(Get-GodModeFileHash $log);proof_bundle=(Get-GodModeFileHash $proofPath)};proof_bundle=$proof;summary='Read-only dry-run mission completed without patching application files.';created_at=Get-GodModeIso}
Submit-GodModeAgentResult $Project $result|Out-Null; Add-GodModeTraceSpan $Project $MissionId 'spawn-agent-dry-run' 'ok' @{role=$Role;log=$log}|Out-Null; Write-Host "[DONE] Result submitted to inbox for $MissionId"
