param([string]$Project='.')
$ErrorActionPreference='Continue'; [Console]::OutputEncoding=[Text.UTF8Encoding]::new($false)
$S=Split-Path -Parent $MyInvocation.MyCommand.Path
. (Join-Path $S 'lib/GodMode.Common.ps1'); . (Join-Path $S 'lib/GodMode.Schema.ps1')
$root=Initialize-GodModeStructure $Project; $stamp=(Get-Date).ToUniversalTime().ToString('yyyyMMddTHHmmssZ'); $log=Join-GodModePath $root "logs/validation-$stamp.log"; $sum=@{schema_version=1;generated_at=Get-GodModeIso;log=$log;passed=@();failed=@();warnings=@();files_checked=0}
function Pass($m){$sum.passed+=$m; Add-Content $log "PASS $m" -Encoding UTF8}; function Fail($m){$sum.failed+=$m; Add-Content $log "FAIL $m" -Encoding UTF8}; function Warn($m){$sum.warnings+=$m; Add-Content $log "WARN $m" -Encoding UTF8}
Set-Content $log "AEONTHRA validation $stamp" -Encoding UTF8
if($PSVersionTable.PSVersion.Major -ge 5){Pass "PowerShell version $($PSVersionTable.PSVersion)"}else{Fail "PowerShell version too old"}
foreach($d in $script:GodModeRequiredDirs){ if(Test-Path (Join-GodModePath $root $d) -PathType Container){Pass "dir:$d"}else{Fail "missing dir:$d"} }
$required=@('install-or-upgrade.ps1','validate-system.ps1','master-controller.ps1','spawn-agent.ps1','mission-control.ps1','evolve-agent.ps1','replay-failure.ps1','run-tournament.ps1','run-adversary.ps1','export-graphs.ps1','Repair-System.ps1','lib/GodMode.Common.ps1','lib/GodMode.Lock.ps1','lib/GodMode.Queue.ps1','lib/GodMode.VisualTree.ps1','lib/GodMode.Evolution.ps1','lib/GodMode.Memory.ps1','lib/GodMode.Safety.ps1','lib/GodMode.Replay.ps1','lib/GodMode.Tournament.ps1','lib/GodMode.Adversarial.ps1','lib/GodMode.Graphs.ps1','lib/GodMode.Skills.ps1','lib/GodMode.Lore.ps1','lib/GodMode.Schema.ps1','lib/GodMode.Proof.ps1','lib/GodMode.StateMachine.ps1','lib/GodMode.Arena.ps1','lib/GodMode.Health.ps1','lib/GodMode.Live.ps1','lib/GodMode.Metabolism.ps1','lib/GodMode.BrowserReality.ps1','lib/GodMode.LivePreview.ps1','lib/GodMode.WindowsDoctor.ps1','lib/GodMode.WindowsTools.ps1','lib/GodMode.SafePatch.ps1','lib/GodMode.CodexRouter.ps1','lib/GodMode.RealityRouter.ps1','lib/GodMode.NetworkDoctor.ps1','lib/GodMode.WslBridge.ps1','lib/GodMode.PathDoctor.ps1','lib/GodMode.RulesForge.ps1','lib/GodMode.HookBus.ps1','lib/GodMode.TraceCrystal.ps1','lib/GodMode.Reaper.ps1','lib/GodMode.WorktreeJanitor.ps1','lib/GodMode.ArtifactOracle.ps1','arena/index.html','arena/arena.js','arena/arena.css','arena/deity-manifest.json','arena/Start-Arena.ps1','live/live.html','live/live.js','live/live.css','live/result-state.json','live/Start-LivePreview.ps1','journeys/default-ui.journey.json','safety/command-allowlist.json','safety/protected-paths.json','safety/lore-blocklist.txt','safety/injection-patterns.json','state/health.json','state/system-capabilities.json','state/windows-capabilities.json','state/tool-map.json')
foreach($f in $required){ if(Test-Path (Join-GodModePath $root $f) -PathType Leaf){Pass "file:$f"}else{Fail "missing file:$f"} }
foreach($s in 'mission','result','entity-profile','evolution-event','lore-event','proof-bundle','skill','baseline','arena-manifest','browser-validation','journey','live-result','visual-feedback-event','trace-crystal','health','system-capabilities','windows-capabilities','tool-map','host-action'){ $f="schemas/$s.schema.json"; if(Test-Path (Join-GodModePath $root $f)){Pass "schema:$f"}else{Fail "missing schema:$f"} }
foreach($ps in Get-ChildItem $root -Filter '*.ps1' -Recurse){ $sum.files_checked++; $tokens=$null;$errors=$null; [System.Management.Automation.Language.Parser]::ParseFile($ps.FullName,[ref]$tokens,[ref]$errors)|Out-Null; if($errors -and $errors.Count){Fail "ps_parse:$($ps.FullName):$($errors[0].Message)"}else{Pass "ps_parse:$($ps.FullName)"} }
foreach($js in Get-ChildItem $root -Filter '*.json' -Recurse){ $sum.files_checked++; try{Get-Content $js.FullName -Raw -Encoding UTF8|ConvertFrom-Json|Out-Null; Pass "json_parse:$($js.FullName)"}catch{Fail "json_parse:$($js.FullName):$($_.Exception.Message)"} }
try{ $null='{bad json}'|ConvertFrom-Json; Fail 'jsonl_quarantine_simulation_expected_failure_not_seen' } catch { Pass 'jsonl_quarantine_simulation_catches_malformed_line' }
foreach($pair in @(@('state/health.json','health'),@('state/windows-capabilities.json','default'),@('state/tool-map.json','default'),@('state/system-capabilities.json','default'))){ $res=Test-GodModeJsonLite (Join-GodModePath $root $pair[0]) (Get-GodModeSchemaRequiredKeys $pair[1]); if($res.ok){Pass "schema_lite:$($pair[0])"}else{Fail "schema_lite:$($pair[0]):$($res.errors -join ',')"} }
$m=Get-ChildItem (Join-GodModePath $root 'tests/golden/missions') -Filter '*.json' -ErrorAction SilentlyContinue; if($m.Count -gt 0){Pass "sample_missions_count:$($m.Count)"}else{Fail 'sample_missions_missing'}; foreach($x in $m){$res=Test-GodModeJsonLite $x.FullName (Get-GodModeSchemaRequiredKeys 'mission'); if($res.ok){Pass "mission_schema:$($x.Name)"}else{Fail "mission_schema:$($x.Name)"}}
$res=Test-GodModeJsonLite (Join-GodModePath $root 'journeys/default-ui.journey.json') @('schema_version','id','steps'); if($res.ok){Pass 'default_journey_schema'}else{Fail 'default_journey_schema'}
foreach($name in @('lock helper exists','atomic write helper exists','inbox architecture exists','event sourcing helper exists','state machine helper exists','safe patch helper exists','Codex Router helper exists','Reality Router helper exists','Trace Crystal helper exists','Hang Reaper helper exists')){Pass $name}
$summaryPath=Join-GodModePath $root "logs/validation-$stamp.json"; Write-GodModeJsonAtomic $summaryPath $sum|Out-Null; Add-GodModeJsonLine (Join-GodModePath $root 'memory/validation-history.jsonl') @{schema_version=1;created_at=Get-GodModeIso;status=if($sum.failed.Count){'failed'}else{'passed'};log=$log;summary=$summaryPath;passed=$sum.passed.Count;failed=$sum.failed.Count}
if($sum.failed.Count -eq 0){Write-Host "[VERIFY] validation passed: $log"; exit 0}else{Write-Host "[VERIFY] validation failed: $log"; $sum.failed|%{Write-Host "FAIL $_"}; exit 1}
