param([int]$Port=7374,[string]$Project='.',[int]$MaxRequests=0)
$ErrorActionPreference='Stop'; [Console]::OutputEncoding=[Text.UTF8Encoding]::new($false)
$GodRoot=Split-Path -Parent $PSScriptRoot; $StateDir=Join-Path $GodRoot 'state'; New-Item -ItemType Directory -Path $StateDir -Force | Out-Null
function Test-PortFree([int]$p){try{$l=[Net.Sockets.TcpListener]::new([Net.IPAddress]::Parse('127.0.0.1'),$p);$l.Start();$l.Stop();$true}catch{$false}}
function Send-HttpResponse([IO.Stream]$Stream,[string]$Status,[string]$ContentType,[byte[]]$Bytes){$header="HTTP/1.1 $Status`r`nContent-Type: $ContentType`r`nCache-Control: no-store`r`nContent-Length: $($Bytes.Length)`r`nConnection: close`r`n`r`n";$hb=[Text.Encoding]::UTF8.GetBytes($header);$Stream.Write($hb,0,$hb.Length);$Stream.Write($Bytes,0,$Bytes.Length)}
function Send-Json([IO.Stream]$Stream,[string]$Status,$Value){$json=$Value|ConvertTo-Json -Depth 20;Send-HttpResponse $Stream $Status 'application/json; charset=utf-8' ([Text.Encoding]::UTF8.GetBytes($json))}
function Get-ContentType([string]$File){$ext=[IO.Path]::GetExtension($File).ToLowerInvariant();if($ext -eq '.html'){return 'text/html; charset=utf-8'}elseif($ext -eq '.js'){return 'text/javascript; charset=utf-8'}elseif($ext -eq '.css'){return 'text/css; charset=utf-8'}elseif($ext -eq '.json'){return 'application/json; charset=utf-8'}else{return 'text/plain; charset=utf-8'}}
function Read-JsonFile($Path,$Default){if(Test-Path -LiteralPath $Path){try{return Get-Content -LiteralPath $Path -Raw -Encoding UTF8|ConvertFrom-Json}catch{return $Default}}return $Default}
function Read-FeedbackEvents{ $file=Join-Path $GodRoot 'live/visual-feedback-events.jsonl'; $routing=Read-JsonFile (Join-Path $StateDir 'visual-feedback-routing.json') @{events=@();rejected=@()}; $map=@{}; foreach($r in @($routing.events)){if($r.event_id){$map[[string]$r.event_id]=$r}}; foreach($r in @($routing.rejected)){if($r.event_id){$map[[string]$r.event_id]=$r}}; $events=@(); if(Test-Path -LiteralPath $file){foreach($line in Get-Content -LiteralPath $file -Encoding UTF8){if([string]::IsNullOrWhiteSpace($line)){continue};try{$e=$line|ConvertFrom-Json;if($map.ContainsKey([string]$e.id)){$e|Add-Member -NotePropertyName routed_status -NotePropertyValue $map[[string]$e.id].routed_status -Force;$e|Add-Member -NotePropertyName mission_id -NotePropertyValue $map[[string]$e.id].mission_id -Force;$e|Add-Member -NotePropertyName resolved -NotePropertyValue $map[[string]$e.id].resolved -Force};$events+=$e}catch{}}}; return $events }
function Get-LatestProof{ $p=Get-ChildItem (Join-Path $GodRoot 'logs') -Recurse -Filter 'browser-proof.json' -ErrorAction SilentlyContinue|Sort-Object LastWriteTime -Descending|Select-Object -First 1; if($p){return Read-JsonFile $p.FullName @{path=$p.FullName}}; return @{schema_version=1;status='missing';message='No browser proof bundle found.'} }
while(-not(Test-PortFree $Port)){$Port++}; Set-Content (Join-Path $StateDir 'arena-port.txt') $Port -Encoding UTF8; $url="http://127.0.0.1:$Port/"; $listener=[Net.Sockets.TcpListener]::new([Net.IPAddress]::Parse('127.0.0.1'),$Port); $listener.Start(); Write-Host "[PREVIEW] Arena server listening on $url"; $count=0
try{while($true){$client=$listener.AcceptTcpClient();$count++;try{$stream=$client.GetStream();$reader=[IO.StreamReader]::new($stream,[Text.Encoding]::UTF8,$false,1024,$true);$req=$reader.ReadLine();while($true){$line=$reader.ReadLine();if($null -eq $line -or $line -eq ''){break}};$target='/';if($req -match 'GET\s+([^\s]+)'){$target=[Uri]::UnescapeDataString($Matches[1].Split('?')[0])};if($target -eq '/'){$target='/index.html'};if($target -eq '/api/visual-feedback'){Send-Json $stream '200 OK' @{ok=$true;events=@(Read-FeedbackEvents)}}elseif($target -eq '/api/latest-proof'){Send-Json $stream '200 OK' (Get-LatestProof)}elseif($target -eq '/api/latest-trace'){Send-Json $stream '200 OK' (Read-JsonFile (Join-Path $StateDir 'latest-trace-summary.json') @{schema_version=1;status='missing'})}else{$map=@{'/index.html'='index.html';'/arena.js'='arena.js';'/arena.css'='arena.css';'/deity-manifest.json'='deity-manifest.json';'/state/health.json'='../state/health.json';'/state/process-registry.json'='../state/process-registry.json';'/state/status-summary.json'='../state/status-summary.json';'/state/validation-status.json'='../state/validation-status.json';'/state/codex-router.json'='../state/codex-router.json';'/state/reality-router.json'='../state/reality-router.json';'/state/worker-smoke.json'='../state/worker-smoke.json';'/state/latest-trace-summary.json'='../state/latest-trace-summary.json';'/state/visual-feedback-routing.json'='../state/visual-feedback-routing.json';'/live/result-state.json'='../live/result-state.json'};$bytes=$null;if($map.ContainsKey($target)){$file=Join-Path $PSScriptRoot $map[$target];if(Test-Path -LiteralPath $file){$bytes=[IO.File]::ReadAllBytes($file);Send-HttpResponse $stream '200 OK' (Get-ContentType $file) $bytes}};if($null -eq $bytes){Send-HttpResponse $stream '404 Not Found' 'text/plain; charset=utf-8' ([Text.Encoding]::UTF8.GetBytes('not found'))}}}finally{$client.Close()};if($MaxRequests -gt 0 -and $count -ge $MaxRequests){break}}}finally{$listener.Stop()}
